### ISSUE TITLE
Kalman Filter problems

### ISSUE THREAD

**Issue by ayr0** [byuimpact/numerical_computing#713] opened 2014-10-27 21:04 UTC
The lab on Kalman Filters should have some specific problems to solve.  As it stands, it is an applications oriented lab that has you simply implement the algorithm, but doesn't ask you solve any actual problems.

**Comment by abefrandsen** [comment] 2015-02-05 19:49
This has been merged with projectile tracking, so the issue is fixed.

**Closed by abefrandsen** 2015-02-05 19:49 UTC
Labels: improvement, retroactive fix, Volume3
